# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Harvy
tagline:          The Cookie monster
url:              http://harvinderatwal.com
paginate:         3
author:
  name:           Harvinder Atwal
  url:            https://twitter.com/harvy2004
  email:          harvinder@harvinderatwal.com
