# Permalinks
permalink:        pretty

# Setup
title:            Harvy
tagline:          The Cookie monster
url:              http://harvinderatwal.com
paginate:         3
baseurl:          /
homepage:         http://harvinderatwal.com
author:
  name:           Harvinder Atwal
  url:            https://twitter.com/harvy2004
  email:          harvinder@harvinderatwal.com
